<script>
    $(document).ready(function(){
        $('#saldo').css({
            float:'right',
            position: 'relative',
            top: '-50px'
        })
        $('table').css({
            border: '1px solid #ccc',
            padding: '5px',
            borderRadius: '10px',
            background: '#f3f6c0'
        })
        $('.botao').css({
            float: 'right',
            marginRight: '20px'
        })
        $('.botao input').css({
            borderRadius: '0 0 5px 5px',
            fontWeight: '600',
            backgroundColor: '#63a9c1',
            color: '#111f46',
            padding: '1px 4px'
        })
        $('form').css({
            width: '410px'
        })
    })
</script>
<h1>Cadastro de Produtos</h1>
<div id="saldo">Quantidade em Estoque: <?= $quant ?></div>
<form method="post" action="../paginas/add.php" />
<table>
    <tr>
        <td align="right">Código</td><td><input name="codigo" type="text" size="10" maxlength="5" required></td><td>&nbsp&nbsp</td>
        <td align="right">Nota Fiscal</td><td><input name="nota" type="text" size="10" maxlength="10" required></td>
    </tr>
    <tr>
        <td align="right">Descrição</td><td colspan="4"><textarea name="descricao" ></textarea></td>
    </tr>
    <tr>
        <td align="right">Valor</td><td><input neme="valor" type="text" size="10" /></td><td></td>
        <td align="right">Entrada</td><td><input name="entrada" type="text" size="10"/></td>
    </tr>
    <tr>
        <td align="right">Loja</td><td><input name="loja" type="text" size="10" /></td><td></td>
    </tr>
</table>
<div class="botao">
    <input type="reset" value="Limpa"/>
    <input type="submit" value="Confirma"/>
</div>
<div id="painel"></div>
</form>